### ISSUE TITLE
petpttx not found

### ISSUE THREAD

**Issue by automatisierungspionier** [sedrew/petpptx#8]
Hi there!
I tried to install `petpptx` with `! pip install petpptx` in Jupyter Notebooks. However I cannot import it, it always gives me `ModuleNotFoundError: No module named 'petpptx'`.
Can you help me debugging this?
Yours
Auto

**Comment by sedrew** [comment]
Hi, This is a fork project, all imports are the same in python-pptx. So just write `import python-pptx`

**Comment by sedrew** [comment]
I have fixed the problems I encountered. Tell me more about your problem. It will be great if you show the part of the code that doesn't work.

**Comment by automatisierungspionier** [comment]
Thanks for your support! 
What I'm trying to do is to figure out an automated solution to update an existing highly formated PowerPoint presentation which contains a business report. So I want to have a Python program that takes some input (let's say a CSV), does some mathematical magic and saves the output to a dedicated Powerpoint presentation / slide / field. 
In the first step I just had a Jupyter notebook parsing my exsiting PowerPoint presentation. For all slides except one the following code gave me `1` which is not the correct number of elements on the slide.

```prs = pptx.Presentation('NAME')
page_id={i+1: slide.slide_id for i, slide in enumerate(prs.slides)}
slide = prs.slides.get(page_id[SLIDE-ID])
len(slide.placeholders)
```

**Comment by automatisierungspionier** [comment]
Hei!
Due to business reasons I can't share the PowerPoint template with you. But I definitly know that there are 3 text boxes on the first slide (like title, subtitle, footer).
```
for el in slide.placeholders:
    print(el.name)
```
gives me
```
Text Placeholder 5
```
though.

**Comment by sedrew** [comment]
Have you solved your problem? I'm closing the Issue
